### ISSUE TITLE
Refine UI

### ISSUE THREAD

**Issue by gexijin** [gexijin/openPay#8]
1. "Open Payment" does not make sense to people right away. Something like Doctors payment or something so that people know right way what we are talking about. 
2. Put explanatory information in a separate tab called "About".  Remove the second text element from the top. 

![image](https://user-images.githubusercontent.com/18232433/203641949-c217a686-4d4a-4128-968d-9feef6eac04e.png)

**Comment by ChrisTret** [comment]
This issue has been resolved, but I do not know how to close the issue. More could certainly be added to the About tab.
